#cloud-config
timezone: Europe/Berlin

package_update: true
package_upgrade: true
packages:
  - unattended-upgrades
  - apt-listchanges
  - docker.io

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [ docker ]

write_files:
  - content: |
      */30 07-23 * * * root docker exec --user www-data nextcloud php occ preview:pre>
      */5 07-23 * * * root docker exec --user www-data nextcloud php -f /var/www/html>
      0 6 1 * * root docker exec --user www-data nextcloud php occ files:scan --all
      0 6 3 * * root docker exec --user www-data nextcloud php occ duplicates:find-all
      0 10 * * * root docker exec --user www-data nextcloud php occ db:add-missing-co>
      0 9 * * * root docker exec --user www-data nextcloud php occ db:add-missing-pri>
      0 * * * * root docker exec --user www-data nextcloud php occ app:update --all ->
      0 5 * * * root reboot
    path: /etc/crontab
    append: true